Code/AastapanaForm_Application/AastapanaForm_Application/Controllers/SectionController.cs
using AastapanaForm_Application.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AastapanaForm_Application.Controllers
{
    public class SectionController : Controller
    {
        Db_AsthapanaEntities db = new Db_AsthapanaEntities();
        // GET: Section
        public ActionResult Section1()
        {
            
                return View();
            
            
        }
        [HttpPost]
        public JsonResult Section1(Tbl_Section model)
        {
            try
            {
                if (model.From > model.To)
                {
                    return Json(new { Result = false, Response = "Select Valid Date" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    model.Login_ID = Session["loginId"].ToString();
                    db.Tbl_Section.Add(model);
                    db.SaveChanges();
                    return Json(new { Result = true, Response = "Submitted" }, JsonRequestBehavior.AllowGet);
                }
                
            }
            catch(Exception ex)
            {
                return Json(new { Result = false, Response = "Something went Wrong" }, JsonRequestBehavior.AllowGet);
            }
           
        }

       

        public ActionResult SectionLogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult printForm(Tbl_Login tbl_Login)
        {
           
            var res = db.Tbl_Login.Where(x => x.Login_ID == tbl_Login.Login_ID).FirstOrDefault();
           
            if(res.Login_ID==tbl_Login.Login_ID && res.Password==tbl_Login.Password)
            {
                TempData["Login"] = res.Login_ID;
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public JsonResult GetSectionData(int ID)
        {
            var res = db.Tbl_Section.Where(x => x.Id == ID).FirstOrDefault();
            return Json(new { Result = true, Response = res }, JsonRequestBehavior.AllowGet);
        }

       
    }
}

Code/AastapanaForm_Application/AastapanaForm_Application/Views/Section/Section2.cshtml
@model AastapanaForm_Application.Models.Tbl_Section2
@{
    ViewBag.Title = "Section2";
    Layout = "~/Views/Shared/DashBoard_Layout.cshtml";
}

<form id="submit_form">


    <div class="container embed-responsive-item" style="margin-left:-10px">
        <div class="row" style="font-size: medium; font-weight: bold; text-align: center; line-height: 30px; padding-top: 10px;">
            Section 2
        </div>
        <br />
        <div class="row" style="border:inset 2px  #3eadcf"></div>
        <br />
        <ul>
            <li> <div class="col-md-12" style="font-weight:bold">आस्थापना शाखेने भरावयाची माहिती To Be Filled in by establishment section</div></li>
        </ul>
        <div class="panel panel-default">

            <br /><br />
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-lg-5">
                    <span>
                        1) धारण केलेल्या पदावरून करणे अपेक्षित असलेल्या कामाचे थोडक्यात विवरण.<br />
                        Brief description of task  required to be performed while holding the post ( 50 शब्द )
                        :
                    </span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-lg-10">
                    <textarea id="TaskDuringPost" name="TaskDuringPost" rows="4" cols="50" style="width:700px;border-color:#b9b4b4"></textarea>
                </div>
            </div>
            <br /><br />

            @*<div class="col-md-1"></div>*@
            <div class="row">

                <div class="col-md-1"></div>
                <div class="col-lg-5">
                    <span>
                        2) वार्षिक / प्रतिवेदनाच्या कलावधिकारिता नेमून दिलेल्या कामाची उद्दिष्टे ( असल्यास ).<br />
                        Allocated tasks ( if any ) for the year or period reported upon
                    </span>
                </div>

            </div>
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-lg-10">
                    <textarea id="AllocatedTask" name="AllocatedTask" rows="4" cols="50" style="width:700px;border-color:#b9b4b4"></textarea>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-lg-5">
                    <span>
                        3) वर्षभरात / सदर कालावधीत पार पाडलेल्या 4-5 महत्वाच्या व उल्लेखनीय कामांचे संक्षिप्त वर्णन .<br />
                        List 4-5 important and noteworthy works done during the period ( 100 शब्दांत  )
                    </span><span style="color:Red">*</span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-lg-10">
                    <textarea id="WorksInWork" name="WorksInWork" rows="4" cols="50" style="width:700px;border-color:#b9b4b4"></textarea>

                </div>
            </div>

            <br />
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-lg-5">
                    <span>
                        4) जी उद्दिष्टे पूर्ण होऊ शकली नाहीत,त्याकरिता आलेल्या अडचणी.<br />
                        Difficulties faced in not achieving certain targets
                    </span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-lg-10">
                    <textarea id="Diffi_In_Targets" name="Diffi_In_Targets" rows="4" cols="50" style="width:700px;border-color:#b9b4b4"></textarea>
                </div>
            </div>

            <br />
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-lg-5">

                    5) कार्यक्षमता वाढविण्याकरिता स्वत: स आवश्यक वाटते असे प्रशिक्षणाचे क्षेत्र.<br />
                    Mention areas of required training which you feel necessary for higher efficieny
                    :

                </div>
            </div>
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-lg-10">
                    <textarea id="Area_Requi_Train" name="Area_Requi_Train" rows="4" cols="50" style="width:700px;border-color:#b9b4b4"></textarea>

                </div>
            </div>
            @*<div class="col-md-1"></div>*@
            <br />
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-lg-5">

                    6)  मागील वर्षाच्या दिनांक 31 मार्च अखेरचे वार्षिक मालमत्ता विवरणपत्र संबंधित प्राधिकार्‍याकडे सादर केले आहे काय ?        ( सादर केले असल्यास दिनांक ).                                                                                                   होय / नाही
                    <br /> Whether assets and liabilities statement ऑफ previous year , submitted to concerned authority ?  (date of submission if submitted )                                                                     yes / no

                </div>
                @Html.HiddenFor(model => model.Id)
                <div class="col-sm-3">
                    <div class="form-group">
                        <div>
                            <label class="radio-inline">
                                @Html.RadioButtonFor(model => model.Asset_Submit_Status, "Yes", new { @id = "Yes" }) Yes
                            </label>
                            <label class="radio-inline">
                                @Html.RadioButtonFor(model => model.Asset_Submit_Status, "No", new { @id = "No" }) No
                            </label>
                        </div>

                    </div>
                </div>
                <br /><br />
            </div>

            <br /><br />
        </div>



    </div>

    <center>
        <input type="button" id="submit_btn" class="btn btn-block btn-primary btn-lg font-weight-bolder auth-form-btn" value="SUBMIT" style="background-color: #3eadcf; width:10%;font-weight:bold">
    </center>


</form>

<script>
    $(document).ready(function () {

        $("#submit_btn").click(function (e) {

            e.preventDefault();
            var formdata = new FormData($(submit_form)[0]);
            $.ajax({
                url: 'Section2',
                type: 'Post',
                datatype: 'json',
                data: formdata,
                processData: false,
                contentType: false,
                success: function (Data) {
                    debugger
                    if (Data.Result) {
                        Success_Alert(Data.Response);
                        $("#submit_form")[0].reset();
                        /*setTimeout(function () { window.location = "../Section/Section3"; }, 4000);*/
                    } else {
                        Error_Alert(Data.Response);
                    }
                },
            });
        });

    });
</script>

Code/AastapanaForm_Application/AastapanaForm_Application/Views/Section/Section4.cshtml
@model AastapanaForm_Application.Models.Tbl_Section4
@{
    ViewBag.Title = "Section4";
    Layout = "~/Views/Shared/DashBoard_Layout.cshtml";
}

<form id="submit_form">
    <div class="container embed-responsive-item" style="margin-left:-10px">
        <div class="row" style="font-size: medium; font-weight: bold; text-align: center; line-height: 30px; padding-top: 10px;">
            Section 4
        </div>
        <br />
        <div class="row" style="border:inset 2px  #3eadcf"></div>
        <br />
        <ul>
            <li>
                <div class="col-md-12" style="font-weight:bold">
                    पुनर्विलोकन  अधिकार्‍याचे  अभिप्राय remarks of reviewing officer
                </div>
            </li>
        </ul>
        <div class="panel panel-default">
            <br /><br />
                  <div class="row">
                      <div class="col-md-1"></div>
                      <div class="col-lg-5">

                          1)  आपण प्रतिवेदन अधिकार्‍याने, संबंधित अधिकारी /कर्मचार्‍याच्या कार्यपूर्तता, कार्यक्षमता, वैयक्तिक गुणवैशिष्ट्ये यासंबंधाने भाग – 3 मधील मुद्यांच्या साह्याने केलेल्या मूल्यनिर्धारणाशी सहमत आहात काय ?
                          Do you agree with assessment of reporting officer on work don, efficiency ,personal attributes in part – 3 concerned officer / employee ?
                          yes / no

                      </div>
                      @Html.HiddenFor(model => model.Id)
                      <div class="col-sm-3">
                          <div class="form-group">
                              <div>
                                  <label class="radio-inline">
                                      @Html.RadioButtonFor(model => model.Agree_assessment_sect3, "Yes", new { @id = "Yes" }) Yes
                                  </label>
                                  <label class="radio-inline">
                                      @Html.RadioButtonFor(model => model.Agree_assessment_sect3, "No", new { @id = "No" }) No
                                  </label>
                              </div>

                          </div>
                      </div>
                  </div>
            <br /><br />
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-lg-5">
                    <span>
                        2) सहमत नसल्यास,तपशील व कारने द्यावीत.<br />
                        In case of difference of opiनिon details and reasons for the same may be given

                        :
                    </span>
                </div>
                <div class="col-lg-3">
                    @Html.TextBoxFor(model => model.Diff_opinion, new { @class = "form-control", @name = "First_Name ", @id = "First_Name", @required = "required" })
                    @Html.ValidationMessageFor(model => model.Diff_opinion, "", new { @class = "text-danger" })

                </div>
            </div>
            <br />
            @*<div class="col-md-1"></div>*@
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-lg-5">
                    <span>
                        2) वार्षिक / प्रतिवेदनाच्या कलावधिकारिता नेमून दिलेल्या कामाची उद्दिष्टे ( असल्यास ).<br />
                        Allocated tasks ( if any ) for the year or period reported upon
                    </span>
                </div>
                <div class="col-lg-3">
                    @Html.EditorFor(model => model.Overall_assessment_officer, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Overall_assessment_officer, "", new { @class = "text-danger" })

                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-lg-5">
                    <span>
                        3) अधिकारी/ कर्मचार्री यांचे एकंदरीत मूल्यमापन ( जास्तीत जास्त 100 शब्द )
                        यामध्ये संबंधित अधिकारी / कर्मचार्‍यांची बलस्थाने , उणिवा  आणि दिव्यांग व्यक्ति , महिला व मागासवर्गीयांबाबतचा दृश्ठिकोण यांचा समावेश असावा.
                        Overall assessment of officer / employee ( maximum 100 words )
                        Include strengths and lesser strengths and his attitude towards disabled persons , women अँड backward क्लाससेस.

                    </span><span style="color:Red">*</span>
                </div>
                <div class="col-lg-3">
                    @Html.EditorFor(model => model.Overall_assessment_officer, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Overall_assessment_officer, "", new { @class = "text-danger" })

                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-lg-5">
                    <span>
                        4) एकंदरीत गुणांकन
                        ( 1- 10 या मर्यादित गुणांकन देण्यात यावे . )
                        Overall gradation
                    </span>
                </div>
                <div class="col-lg-5">
                    @Html.DropDownListFor(model => model.Overall_graduation, new List<SelectListItem>
                           {
                           new SelectListItem { Text = "1 ", Value = "1"},
                           new SelectListItem { Text = "2 ", Value = "2"},
                           new SelectListItem { Text = "3", Value = "3"},
                           new SelectListItem { Text ="4", Value ="4"},
                           new SelectListItem { Text = "5", Value = "5"},
                            new SelectListItem { Text = " 6 ", Value = " 6 "},
                           new SelectListItem { Text = "  7 ", Value = " 7 "},
                           new SelectListItem { Text = "  8 ", Value = " 8 "},
                           new SelectListItem { Text ="   9 ", Value ="  9 "},
                           new SelectListItem { Text = "  10 ", Value = " 10 "},

                          }, "-Select Overall Gradation -", new { @class = "btn btn-default dropdown-toggle", @style = "width:210px" })

                </div>
            </div>
            <br />
            <br /><br /><br />
            <center>
                <input type="button" id="submit_btn" class="btn btn-block btn-primary btn-lg font-weight-bolder auth-form-btn" value="SUBMIT" style="background-color: #3eadcf;font-weight:bold; width:15%">
            </center>
        </div>

    </div>
    

</form>

<script>
    $(document).ready(function () {
       
        $("#submit_btn").click(function (e) {

            e.preventDefault();
            var formdata = new FormData($(submit_form)[0]);
            $.ajax({
                url: 'Section4',
                type: 'Post',
                datatype: 'json',
                data: formdata,
                processData: false,
                contentType: false,
                success: function (Data) {
                    debugger
                    if (Data.result) {
                        alert(Data.Response);
                    }


                },
            });
        });

    });
</script>

Code/AastapanaForm_Application/AastapanaForm_Application/Views/Section/SectionLogin.cshtml
@{
    ViewBag.Title = "SectionLogin";
}


<style>
    @@import url(http://fonts.googleapis.com/css?family=Roboto:400,100);

    body {
        background: url(https://dl.dropboxusercontent.com/u/23299152/Wallpapers/wallpaper-22705.jpg) no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
        font-family: 'Roboto', sans-serif;
    }

    .login-card {
        padding: 40px;
        width: 274px;
        background-color: #F7F7F7;
        margin: 0 auto 10px;
        border-radius: 2px;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        overflow: hidden;
    }

        .login-card h1 {
            font-weight: 100;
            text-align: center;
            font-size: 2.3em;
        }

        .login-card input[type=submit] {
            width: 100%;
            display: block;
            margin-bottom: 10px;
            position: relative;
        }

        .login-card input[type=text], input[type=password] {
            height: 44px;
            font-size: 16px;
            width: 100%;
            margin-bottom: 10px;
            -webkit-appearance: none;
            background: #fff;
            border: 1px solid #d9d9d9;
            border-top: 1px solid #c0c0c0;
            /* border-radius: 2px; */
            padding: 0 8px;
            box-sizing: border-box;
            -moz-box-sizing: border-box;
        }

            .login-card input[type=text]:hover, input[type=password]:hover {
                border: 1px solid #b9b9b9;
                border-top: 1px solid #a0a0a0;
                -moz-box-shadow: inset 0 1px 2px rgba(0,0,0,0.1);
                -webkit-box-shadow: inset 0 1px 2px rgba(0,0,0,0.1);
                box-shadow: inset 0 1px 2px rgba(0,0,0,0.1);
            }

    .login {
        text-align: center;
        font-size: 14px;
        font-family: 'Arial', sans-serif;
        font-weight: 700;
        height: 36px;
        padding: 0 8px;
        /* border-radius: 3px; */
        /* -webkit-user-select: none;
        user-select: none; */
    }

    .login-submit {
        /* border: 1px solid #3079ed; */
        border: 0px;
        color: #fff;
        text-shadow: 0 1px rgba(0,0,0,0.1);
        background-color: #4d90fe;
        /* background-image: -webkit-gradient(linear, 0 0, 0 100%,   from(#4d90fe), to(#4787ed)); */
    }

        .login-submit:hover {
            /* border: 1px solid #2f5bb7; */
            border: 0px;
            text-shadow: 0 1px rgba(0,0,0,0.3);
            background-color: #357ae8;
            /* background-image: -webkit-gradient(linear, 0 0, 0 100%,   from(#4d90fe), to(#357ae8)); */
        }

    .login-card a {
        text-decoration: none;
        color: #666;
        font-weight: 400;
        text-align: center;
        display: inline-block;
        opacity: 0.6;
        transition: opacity ease 0.5s;
    }

        .login-card a:hover {
            opacity: 1;
        }

    .login-help {
        width: 100%;
        text-align: center;
        font-size: 12px;
    }

    select {
        width: 190px;
        font-size: 12px;
        height: 34px;
        border-color: #d7cdcd;
        color: gray;
    }
</style>


<div class="login-card">
    <h1>Log-in</h1><br>
    @using (Html.BeginForm("printForm", "Section", FormMethod.Post))
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <label class="text-info ">Enter Login ID :</label><br>
        <input type="text" name="Login_ID" id="Login_ID" class="form-control">
        <br />
        <label class="text-info">Enter Password:</label><br>
        <input type="text" name="Password" id="Password" class="form-control">

        <input type="submit" name="login" class="login login-submit" value="Login">
        <span style="color:green">@TempData["Msg"]</span>
    }

    <div class="login-help">
        <a href="/Register/forget_password">
            Forgot Password
        </a>
    </div>
</div>